@url = http://localhost:4000

POST {{url}}/jobs
Accept: application/json
Content-Type: application/json

{
   "type": "EMAIL",
   "payload": {
      "subject": "My Life",
      "message": "I love my life",
      "recipient": "love@life.com"
   },
   "priority": "LOW"
   # "scheduledAt": "2026-08-25T14:30:00.000Z"
}

### Get Jobs
GET {{url}}/jobs
Accept: application/json
Content-Type: application/json

{
   "take": 1
}

###
GET {{url}}/jobs/deadletters
Accept: application/json

###
GET {{url}}/jobs/deadletters/cmt4g2iwj0000k4pwd0qvhru1
Accept: application/json

###
DELETE  {{url}}/jobs/deadletters/cmt46kund0000p3pwvsxdkiph/retry

Accept: application/json
Content-Type: application/json

### Cancel Job
POST {{url}}/jobs/808611e6-c343-4773-b461-79b000402bd8/cancel
Accept: application/json