-- CreateTable
CREATE TABLE `Job` (
    `id` VARCHAR(191) NOT NULL,
    `type` ENUM('EMAIL', 'REPORT', 'NOTIFICATION') NOT NULL,
    `payload` JSON NOT NULL,
    `status` ENUM('PENDING', 'QUEUED', 'PROCESSING', 'SUCCESS', 'COMPLETED', 'FAILED', 'RETRY', 'DEAD_LETTER') NOT NULL DEFAULT 'PENDING',
    `priority` ENUM('HIGH', 'LOW', 'NORMAL') NOT NULL DEFAULT 'LOW',
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
